### PR TITLE
Issue #150 - display the discount codes int Contact Code Redeemed tab

### PR DESCRIPTION
**Pull request by samuelsov**
cf. https://github.com/dlobo/org.civicrm.module.cividiscount/issues/150

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
this is stale :-(

**Comment by colemanw** [comment]
@samuelsov sorry for the delay. Can you please rebase this so it can be merged?

**Comment by samuelsov** [comment]
Hmm, i'm not very good with those rebase stuff... i will have to remake a new PR

**Comment by samuelsov** [comment]
Ok, i have created a new PR for this... https://github.com/dlobo/org.civicrm.module.cividiscount/pull/158

**Pull request closed without merging**
