### PR TITLE
Age high and low values were transposed

### PR DESCRIPTION
**Pull request by zorgalina**
Admin fields for autodiscount filter on contact age range were transposed

### CODE REVIEW

**Comment by colemanw** [comment]
I wonder what impact this change will have on people who have already set-up these discounts?

**Comment by zorgalina** [comment]
I am trying to test this (latest WP + CiviCRM 4.6.8 base), using 'contact'
as entity and a specific contact_id. I put a try block around the call to
civicrm_api3 in DiscountCalculator:function checkDiscountsByEntity and
passing autodiscount params from cividiscount_item, e.g. 'birth_date_high'
as '50 years' get an exception (that '50 years' isn't a date).
I could code something to specifically handle these values but wasn't sure
if that was needed as docs just suggest 'careful testing' but not, say,
substitution of the year value w/a date.

I tried it in the  Civi 4.6 Drupal 'sandbox' and set an age range but the
auto-discount I set up (again for a specific contact_id) seemed to be
applied regardless of the contact's birthdate.

But, yes, I'd wonder too whether this will cause trouble for existing
installations.
  Is there some way in which the range values 'low' and 'high' could be
interpreted as, well, their opposites?  I saw that the value I picked for
'high' (50 years old) was assigned to birth_date_low, and the one I picked
for 'low' (10 years old) was assigned to birth_date_high.  In the worst
case, a client using these values could run a sql script/patch to fix their
data.

On Fri, Oct 9, 2015 at 4:43 PM, colemanw <notifications@github.com> wrote:

> I wonder what impact this change will have on people who have already
> set-up these discounts?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dlobo/org.civicrm.module.cividiscount/pull/125#issuecomment-147012128>
> .
>



-- 
زورگلنه ءء لسلی

**Comment by zorgalina** [comment]
coleman - I can write a sql script to fix  birth_date filter in
autodiscount rows - but what I would say w/r/t impact on existing configs -
how could it have worked correctly?

On Fri, Oct 9, 2015 at 5:56 PM, Lesley Evensen <zorgalina@gmail.com> wrote:

> I am trying to test this (latest WP + CiviCRM 4.6.8 base), using 'contact'
> as entity and a specific contact_id. I put a try block around the call to
> civicrm_api3 in DiscountCalculator:function checkDiscountsByEntity and
> passing autodiscount params from cividiscount_item, e.g. 'birth_date_high'
> as '50 years' get an exception (that '50 years' isn't a date).
> I could code something to specifically handle these values but wasn't sure
> if that was needed as docs just suggest 'careful testing' but not, say,
> substitution of the year value w/a date.
>
> I tried it in the  Civi 4.6 Drupal 'sandbox' and set an age range but the
> auto-discount I set up (again for a specific contact_id) seemed to be
> applied regardless of the contact's birthdate.
>
> But, yes, I'd wonder too whether this will cause trouble for existing
> installations.
>   Is there some way in which the range values 'low' and 'high' could be
> interpreted as, well, their opposites?  I saw that the value I picked for
> 'high' (50 years old) was assigned to birth_date_low, and the one I picked
> for 'low' (10 years old) was assigned to birth_date_high.  In the worst
> case, a client using these values could run a sql script/patch to fix their
> data.
>
> On Fri, Oct 9, 2015 at 4:43 PM, colemanw <notifications@github.com> wrote:
>
>> I wonder what impact this change will have on people who have already
>> set-up these discounts?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/dlobo/org.civicrm.module.cividiscount/pull/125#issuecomment-147012128>
>> .
>>
>
>
>
> --
> زورگلنه ءء لسلی
>



-- 
زورگلنه ءء لسلی

**Comment by colemanw** [comment]
I haven't forgotten about this. But while testing I found some other things that weren't working and am still investigating. WIP at https://github.com/civicrm/civicrm-core/pull/6934

**Comment by zorgalina** [comment]
Thanks coleman!

On Sun, Oct 11, 2015 at 4:24 PM, colemanw <notifications@github.com> wrote:

> I haven't forgotten about this. But while testing I found some other
> things that weren't working and am still investigating. WIP at
> civicrm/civicrm-core#6934
> <https://github.com/civicrm/civicrm-core/pull/6934>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dlobo/org.civicrm.module.cividiscount/pull/125#issuecomment-147255089>
> .
>



-- 
زورگلنه ءء لسلی

**Comment by zorgalina** [comment]
Looking into details of how contact.birth_date can be filtered for discount
it appears that 1.) the parameter needs to be tagged as/named as a 'filter'
so ultimately it is handled in utils.php:function
_civicrm_api3_apply_filters_to_dao; and 2.) the value should not be set as
simply '10 years' or '65 years' as in discount_item.autodiscount, but an
actual date, since the 'high/low' values there are compared using operators
>= or <= and not date functions.
  That explains (to me) why the discount code high/low values were
transposed, since the api/utils filter code is coded to compare ordinal
values and not dates/age where 'high' values are ordinally lower.  However,
it seems the values still need to be converted to actual SQL dates (e.g.
'1960-10-13'), perhaps using Jan 1 for month-day.
  I can work on a fix for this, if this sounds like it makes sense. From a
design/arch. standpoint, though, I'd say the api/utils should be enhanced
to filter date differences differently than ordinal numeric values.

On Mon, Oct 12, 2015 at 1:45 PM, Lesley Evensen <zorgalina@gmail.com> wrote:

> Thanks coleman!
>
> On Sun, Oct 11, 2015 at 4:24 PM, colemanw <notifications@github.com>
> wrote:
>
>> I haven't forgotten about this. But while testing I found some other
>> things that weren't working and am still investigating. WIP at
>> civicrm/civicrm-core#6934
>> <https://github.com/civicrm/civicrm-core/pull/6934>
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/dlobo/org.civicrm.module.cividiscount/pull/125#issuecomment-147255089>
>> .
>>
>
>
>
> --
> زورگلنه ءء لسلی
>



-- 
زورگلنه ءء لسلی

**Comment by colemanw** [comment]
The api is supposed to accept any date string understood by `strtotime` so 'now + 10 years' is perfectly acceptable to the api.

**Comment by zorgalina** [comment]
If column names are reliably named '*date' (activity_date_time, birth_date,
created_date..) then _civicrm_api3_apply_filters_to_dao can do something
like the following:
if (strstr($fieldName, 'date')) {
      $dao->whereAdd("($fieldName <= $filtervalue)");
    } else {
      $dao->whereAdd("($fieldName >= $filterValue )");
    }
but that would mean users who have used already used the API w/date fields
would be turned around. To avoid that problem, maybe add a new function
named  _civicrm_api3_apply_date_filters_to_dao  - you-all may've
encountered issues like this before and have a way to address them

On Tue, Oct 13, 2015 at 11:19 AM, Lesley Evensen <zorgalina@gmail.com>
wrote:

> Looking into details of how contact.birth_date can be filtered for
> discount it appears that 1.) the parameter needs to be tagged as/named as a
> 'filter' so ultimately it is handled in utils.php:function
> _civicrm_api3_apply_filters_to_dao; and 2.) the value should not be set as
> simply '10 years' or '65 years' as in discount_item.autodiscount, but an
> actual date, since the 'high/low' values there are compared using operators
> >= or <= and not date functions.
>   That explains (to me) why the discount code high/low values were
> transposed, since the api/utils filter code is coded to compare ordinal
> values and not dates/age where 'high' values are ordinally lower.  However,
> it seems the values still need to be converted to actual SQL dates (e.g.
> '1960-10-13'), perhaps using Jan 1 for month-day.
>   I can work on a fix for this, if this sounds like it makes sense. From a
> design/arch. standpoint, though, I'd say the api/utils should be enhanced
> to filter date differences differently than ordinal numeric values.
>
> On Mon, Oct 12, 2015 at 1:45 PM, Lesley Evensen <zorgalina@gmail.com>
> wrote:
>
>> Thanks coleman!
>>
>> On Sun, Oct 11, 2015 at 4:24 PM, colemanw <notifications@github.com>
>> wrote:
>>
>>> I haven't forgotten about this. But while testing I found some other
>>> things that weren't working and am still investigating. WIP at
>>> civicrm/civicrm-core#6934
>>> <https://github.com/civicrm/civicrm-core/pull/6934>
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/dlobo/org.civicrm.module.cividiscount/pull/125#issuecomment-147255089>
>>> .
>>>
>>
>>
>>
>> --
>> زورگلنه ءء لسلی
>>
>
>
>
> --
> زورگلنه ءء لسلی
>



-- 
زورگلنه ءء لسلی

**Comment by zorgalina** [comment]
OK - so it is meant to subtract (now - 5 years) to get these values



On Tue, Oct 13, 2015 at 11:47 AM, colemanw <notifications@github.com> wrote:

> The api is supposed to accept any date string understood by strtotime so
> 'now + 10 years' is perfectly acceptable to the api.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dlobo/org.civicrm.module.cividiscount/pull/125#issuecomment-147810140>
> .
>



-- 
زورگلنه ءء لسلی

**Comment by colemanw** [comment]
@eileenmcnaughton you were just testing these out - did you happen to try this filter? Any opinions on this fix?

**Comment by eileenmcnaughton** [comment]
I thought it worked for me when I tested it - I didn't add the word 'years' - just the number 3 I think...

**Comment by zorgalina** [comment]
I didn't add the word 'years', it was added in the code in the
cividiscount_item.autodiscount string, after I selected a range from 15 to
50 on my local install.
After setting a birthdate for the 'demo' contact in the 4.6 Drupal sandbox,
and setting up an autodiscount code I never got the automatic discount.  If
you can try it on there (http://dmaster.demo.civicrm.org/) and get a
discount for an event (I tried the Fall Fundraiser Dinner, and then created
a new event w/a price set I created, no discounts), I'll give you a
discount!
The sandbox shows it is using 3.1 of cividiscount..
thanks

On Tue, Oct 13, 2015 at 3:26 PM, Eileen McNaughton <notifications@github.com
> wrote:

> I thought it worked for me when I tested it - I didn't add the word
> 'years' - just the number 3 I think...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dlobo/org.civicrm.module.cividiscount/pull/125#issuecomment-147871747>
> .
>



-- 
زورگلنه ءء لسلی

**Comment by zorgalina** [comment]
Also - line 176, DiscountCalculator.php, should that be:
if ( $this->entity == 'membership' || $this->entity == 'event')
?

On Tue, Oct 13, 2015 at 4:36 PM, Lesley Evensen <zorgalina@gmail.com> wrote:

> I didn't add the word 'years', it was added in the code in the
> cividiscount_item.autodiscount string, after I selected a range from 15 to
> 50 on my local install.
> After setting a birthdate for the 'demo' contact in the 4.6 Drupal
> sandbox, and setting up an autodiscount code I never got the automatic
> discount.  If you can try it on there (http://dmaster.demo.civicrm.org/)
> and get a discount for an event (I tried the Fall Fundraiser Dinner, and
> then created a new event w/a price set I created, no discounts), I'll give
> you a discount!
> The sandbox shows it is using 3.1 of cividiscount..
> thanks
>
> On Tue, Oct 13, 2015 at 3:26 PM, Eileen McNaughton <
> notifications@github.com> wrote:
>
>> I thought it worked for me when I tested it - I didn't add the word
>> 'years' - just the number 3 I think...
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/dlobo/org.civicrm.module.cividiscount/pull/125#issuecomment-147871747>
>> .
>>
>
>
>
> --
> زورگلنه ءء لسلی
>



-- 
زورگلنه ءء لسلی

**Comment by zorgalina** [comment]
The age range filter does work as coded (low date = high age and ages
are converted to current date - age in years for the  api query).

 However, for Contact Type, CRM/Contact/BAO/Query.php line 1604 inserts
'IN' (where the sql query is formatted for a 'where' clause as
'contact_type IN ' values), but CiviDiscount/CRM/ Admin.php already put
'IN' as an operator for  'contact_type'
(Admin.php line 634).
 I set up a discount with contact_type = 'Individual'; and later added
'Household' and the api formed. a query with 2 'IN's

On Wed, Oct 14, 2015 at 12:33 PM, Lesley Evensen <zorgalina@gmail.com>
wrote:

> Also - line 176, DiscountCalculator.php, should that be:
> if ( $this->entity == 'membership' || $this->entity == 'event')
> ?
>
> On Tue, Oct 13, 2015 at 4:36 PM, Lesley Evensen <zorgalina@gmail.com>
> wrote:
>
>> I didn't add the word 'years', it was added in the code in the
>> cividiscount_item.autodiscount string, after I selected a range from 15 to
>> 50 on my local install.
>> After setting a birthdate for the 'demo' contact in the 4.6 Drupal
>> sandbox, and setting up an autodiscount code I never got the automatic
>> discount.  If you can try it on there (http://dmaster.demo.civicrm.org/)
>> and get a discount for an event (I tried the Fall Fundraiser Dinner, and
>> then created a new event w/a price set I created, no discounts), I'll give
>> you a discount!
>> The sandbox shows it is using 3.1 of cividiscount..
>> thanks
>>
>> On Tue, Oct 13, 2015 at 3:26 PM, Eileen McNaughton <
>> notifications@github.com> wrote:
>>
>>> I thought it worked for me when I tested it - I didn't add the word
>>> 'years' - just the number 3 I think...
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/dlobo/org.civicrm.module.cividiscount/pull/125#issuecomment-147871747>
>>> .
>>>
>>
>>
>>
>> --
>> زورگلنه ءء لسلی
>>
>
>
>
> --
> زورگلنه ءء لسلی
>



-- 
زورگلنه ءء لسلی

**Comment by eileenmcnaughton** [comment]
The contact_type IN thing has been recently patched in core - although I don't know if the patch went onto 4.7 or 4.6 @monishdeb @colemanw  either of you know?

**Comment by colemanw** [comment]
Sounds like this can be closed if it's working as-is. For the contact_type fix see https://github.com/civicrm/civicrm-core/pull/6934 which is for 4.7 (might be difficult to back-port to 4.6 because it relies on some other BAO restructuring done in 4.7)

**Comment by zorgalina** [comment]
ok, thank you, Eileen! I'll look for the patch

On Thu, Oct 15, 2015 at 4:51 PM, Eileen McNaughton <notifications@github.com
> wrote:

> The contact_type IN thing has been recently patched in core - although I
> don't know if the patch went onto 4.7 or 4.6 @monishdeb
> <https://github.com/monishdeb> @colemanw <https://github.com/colemanw>
> either of you know?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dlobo/org.civicrm.module.cividiscount/pull/125#issuecomment-148555120>
> .
>



-- 
زورگلنه ءء لسلی

**Comment by zorgalina** [comment]
thanks, all

On Thu, Oct 15, 2015 at 7:55 PM, colemanw <notifications@github.com> wrote:

> Sounds like this can be closed if it's working as-is. For the contact_type
> fix see civicrm/civicrm-core#6934
> <https://github.com/civicrm/civicrm-core/pull/6934> which is for 4.7
> (might be difficult to back-port to 4.6 because it relies on some other BAO
> restructuring done in 4.7)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dlobo/org.civicrm.module.cividiscount/pull/125#issuecomment-148583912>
> .
>



-- 
زورگلنه ءء لسلی

**Pull request closed without merging**
