### PR TITLE
Add back _cividiscount_get_discounted_event_ids

### PR DESCRIPTION
**Pull request by zorgalina**

### CODE REVIEW

**Comment by colemanw** [comment]
This PR appears to be attempting to merge the 4.5 branch into the 4.4 branch.

**Comment by zorgalina** [comment]
My mistake - my intent was to fork from the 'advanced_filter' branch
created by Eileen McNaughton, where this function was missing

On Sun, Apr 19, 2015 at 7:34 AM, colemanw <notifications@github.com> wrote:

> This PR appears to be attempting to merge the 4.5 branch into the 4.4
> branch.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dlobo/org.civicrm.module.cividiscount/pull/91#issuecomment-94282547>
> .
>



-- 
زورگلنه ءء لسلی

**Comment by zorgalina** [comment]
I issued a fork command from here:
https://github.com/eileenmcnaughton/org.civicrm.module.cividiscount

On Sun, Apr 19, 2015 at 7:54 AM, Lesley Evensen <zorgalina@gmail.com> wrote:

> My mistake - my intent was to fork from the 'advanced_filter' branch
> created by Eileen McNaughton, where this function was missing
>
> On Sun, Apr 19, 2015 at 7:34 AM, colemanw <notifications@github.com>
> wrote:
>
>> This PR appears to be attempting to merge the 4.5 branch into the 4.4
>> branch.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/dlobo/org.civicrm.module.cividiscount/pull/91#issuecomment-94282547>
>> .
>>
>
>
>
> --
> زورگلنه ءء لسلی
>



-- 
زورگلنه ءء لسلی

**Comment by zorgalina** [comment]
Should I 'close' this PR?   From what I have read re: github, that should
solve this problem.
 When I did the PR, I referenced the 4.4 branch, but obvs. I messed up.

On Sun, Apr 19, 2015 at 7:34 AM, colemanw <notifications@github.com> wrote:

> This PR appears to be attempting to merge the 4.5 branch into the 4.4
> branch.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dlobo/org.civicrm.module.cividiscount/pull/91#issuecomment-94282547>
> .
>



-- 
زورگلنه ءء لسلی

**Comment by colemanw** [comment]
Yes please open a new pr against the intended branch.

**Comment by zorgalina** [comment]
I did, thank you, and it has been integrated (by Eileen McNaughton). I
closed the PR I made in error that you emailed about

On Mon, Apr 20, 2015 at 8:29 AM, colemanw <notifications@github.com> wrote:

> Yes please open a new pr against the intended branch.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dlobo/org.civicrm.module.cividiscount/pull/91#issuecomment-94484084>
> .
>



-- 
زورگلنه ءء لسلی

**Pull request closed without merging**
